# Form implementation generated from reading ui file 'Database/database_navigator.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DatabaseNavigatorWidget(object):
    def setupUi(self, DatabaseNavigatorWidget):
        DatabaseNavigatorWidget.setObjectName("DatabaseNavigatorWidget")
        DatabaseNavigatorWidget.resize(580, 586)
        DatabaseNavigatorWidget.setStyleSheet("QWidget{\n"
"background-color: rgb(230,230,230);\n"
"\n"
"}\n"
"\n"
"QPushButton {\n"
"     background-color: rgb(255,255,255);     /* Background color */\n"
"     color: rgb(0, 0, 150);     /* Text color */\n"
"     border: 2px solid rgb(255,155, 50);     /* Border color */\n"
"     border-radius: 5px;     /* Rounded edges */\n"
"     padding: 2px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"     background-color: rgb(245, 245, 255);     /* Background color when hovered */\n"
"     color: rgb(0, 0, 200);\n"
"     border-color:rgb(225, 105, 0);     /* Border color when hovered */\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"  background-color: rgb(200,200, 210);     /* Background color when pressed */\n"
"     border: 3px solid rgb(205, 85, 0);\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"     background-color: rgb(220,220, 220);\n"
"     border: 3px solid rgb(205, 105, 0);\n"
"     font-weight: bold;     /* Bold text */\n"
"}\n"
"\n"
"QGroupBox{\n"
"color: rgb(0, 0, 150);     /* Text color */\n"
"font-weight: bold;     /* Bold text */\n"
"}\n"
"\n"
"QLabel{\n"
"color: rgb(0, 0, 150);     /* Text color */\n"
"}\n"
"\n"
"QLineEdit, QDoubleSpinBox, QSpinBox {\n"
"background-color: rgb(255,255,255);\n"
"color: rgb(0, 0, 150);     /* Text color */\n"
"border: 2px solid rgb(255,155,50);     /* Border color */\n"
"border-radius: 5px;     /* Rounded edges */\n"
"padding : 2px;\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(DatabaseNavigatorWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.palette_group = QtWidgets.QGroupBox(parent=DatabaseNavigatorWidget)
        self.palette_group.setObjectName("palette_group")
        self.palette_layout = QtWidgets.QGridLayout(self.palette_group)
        self.palette_layout.setObjectName("palette_layout")
        self.editor_group = QtWidgets.QGroupBox(parent=self.palette_group)
        self.editor_group.setObjectName("editor_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.editor_group)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_color_name = QtWidgets.QLabel(parent=self.editor_group)
        self.label_color_name.setObjectName("label_color_name")
        self.gridLayout_2.addWidget(self.label_color_name, 0, 0, 1, 1)
        self.save_params_btn = QtWidgets.QPushButton(parent=self.editor_group)
        self.save_params_btn.setObjectName("save_params_btn")
        self.gridLayout_2.addWidget(self.save_params_btn, 16, 0, 1, 1)
        self.label_hatch = QtWidgets.QLabel(parent=self.editor_group)
        self.label_hatch.setObjectName("label_hatch")
        self.gridLayout_2.addWidget(self.label_hatch, 5, 0, 1, 1)
        self.label_power = QtWidgets.QLabel(parent=self.editor_group)
        self.label_power.setObjectName("label_power")
        self.gridLayout_2.addWidget(self.label_power, 9, 0, 1, 1)
        self.color_layout = QtWidgets.QHBoxLayout()
        self.color_layout.setObjectName("color_layout")
        self.color_rgb_btn = QtWidgets.QPushButton(parent=self.editor_group)
        self.color_rgb_btn.setText("")
        self.color_rgb_btn.setObjectName("color_rgb_btn")
        self.color_layout.addWidget(self.color_rgb_btn)
        self.color_rgb_label = QtWidgets.QLabel(parent=self.editor_group)
        self.color_rgb_label.setObjectName("color_rgb_label")
        self.color_layout.addWidget(self.color_rgb_label)
        self.gridLayout_2.addLayout(self.color_layout, 3, 0, 1, 2)
        self.label_color_rgb = QtWidgets.QLabel(parent=self.editor_group)
        self.label_color_rgb.setObjectName("label_color_rgb")
        self.gridLayout_2.addWidget(self.label_color_rgb, 2, 0, 1, 1)
        self.label_hatch_pattern = QtWidgets.QLabel(parent=self.editor_group)
        self.label_hatch_pattern.setObjectName("label_hatch_pattern")
        self.gridLayout_2.addWidget(self.label_hatch_pattern, 7, 0, 1, 1)
        self.hatch_dist_spinbox = QtWidgets.QDoubleSpinBox(parent=self.editor_group)
        self.hatch_dist_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.hatch_dist_spinbox.setDecimals(2)
        self.hatch_dist_spinbox.setMaximum(1000.0)
        self.hatch_dist_spinbox.setObjectName("hatch_dist_spinbox")
        self.gridLayout_2.addWidget(self.hatch_dist_spinbox, 6, 0, 1, 2)
        self.laser_power_spinbox = QtWidgets.QDoubleSpinBox(parent=self.editor_group)
        self.laser_power_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.laser_power_spinbox.setDecimals(1)
        self.laser_power_spinbox.setMaximum(100.0)
        self.laser_power_spinbox.setProperty("value", 10.0)
        self.laser_power_spinbox.setObjectName("laser_power_spinbox")
        self.gridLayout_2.addWidget(self.laser_power_spinbox, 11, 0, 1, 1)
        self.hatch_pattern_combo = QtWidgets.QComboBox(parent=self.editor_group)
        self.hatch_pattern_combo.setObjectName("hatch_pattern_combo")
        self.gridLayout_2.addWidget(self.hatch_pattern_combo, 8, 0, 1, 1)
        self.color_name_edit = QtWidgets.QLineEdit(parent=self.editor_group)
        self.color_name_edit.setObjectName("color_name_edit")
        self.gridLayout_2.addWidget(self.color_name_edit, 1, 0, 1, 2)
        self.label_hatch_angle = QtWidgets.QLabel(parent=self.editor_group)
        self.label_hatch_angle.setObjectName("label_hatch_angle")
        self.gridLayout_2.addWidget(self.label_hatch_angle, 7, 1, 1, 1)
        self.hatch_angle_spinbox = QtWidgets.QSpinBox(parent=self.editor_group)
        self.hatch_angle_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.hatch_angle_spinbox.setMaximum(179)
        self.hatch_angle_spinbox.setProperty("value", 90)
        self.hatch_angle_spinbox.setObjectName("hatch_angle_spinbox")
        self.gridLayout_2.addWidget(self.hatch_angle_spinbox, 8, 1, 1, 1)
        self.speed_spinbox = QtWidgets.QDoubleSpinBox(parent=self.editor_group)
        self.speed_spinbox.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.speed_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.speed_spinbox.setDecimals(0)
        self.speed_spinbox.setMaximum(400.0)
        self.speed_spinbox.setProperty("value", 10.0)
        self.speed_spinbox.setObjectName("speed_spinbox")
        self.gridLayout_2.addWidget(self.speed_spinbox, 11, 1, 1, 1)
        self.label_speed = QtWidgets.QLabel(parent=self.editor_group)
        self.label_speed.setObjectName("label_speed")
        self.gridLayout_2.addWidget(self.label_speed, 9, 1, 1, 1)
        self.palette_layout.addWidget(self.editor_group, 0, 2, 1, 1)
        self.color_grid_layout = QtWidgets.QGridLayout()
        self.color_grid_layout.setObjectName("color_grid_layout")
        self.palette_layout.addLayout(self.color_grid_layout, 0, 0, 2, 1)
        self.color_button_layout = QtWidgets.QVBoxLayout()
        self.color_button_layout.setObjectName("color_button_layout")
        self.add_color_btn = QtWidgets.QPushButton(parent=self.palette_group)
        self.add_color_btn.setObjectName("add_color_btn")
        self.color_button_layout.addWidget(self.add_color_btn)
        self.remove_color_btn = QtWidgets.QPushButton(parent=self.palette_group)
        self.remove_color_btn.setObjectName("remove_color_btn")
        self.color_button_layout.addWidget(self.remove_color_btn)
        self.palette_layout.addLayout(self.color_button_layout, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.palette_layout.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.palette_group, 2, 0, 1, 1)
        self.selection_button_box = QtWidgets.QDialogButtonBox(parent=DatabaseNavigatorWidget)
        self.selection_button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.selection_button_box.setObjectName("selection_button_box")
        self.gridLayout.addWidget(self.selection_button_box, 3, 0, 1, 1)
        self.nav_group = QtWidgets.QGroupBox(parent=DatabaseNavigatorWidget)
        self.nav_group.setObjectName("nav_group")
        self.nav_layout = QtWidgets.QGridLayout(self.nav_group)
        self.nav_layout.setObjectName("nav_layout")
        self.laser_combo = QtWidgets.QComboBox(parent=self.nav_group)
        self.laser_combo.setObjectName("laser_combo")
        self.nav_layout.addWidget(self.laser_combo, 0, 1, 1, 1)
        self.label_laser = QtWidgets.QLabel(parent=self.nav_group)
        self.label_laser.setObjectName("label_laser")
        self.nav_layout.addWidget(self.label_laser, 0, 0, 1, 1)
        self.remove_laser_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.remove_laser_btn.setObjectName("remove_laser_btn")
        self.nav_layout.addWidget(self.remove_laser_btn, 0, 4, 1, 1)
        self.add_laser_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.add_laser_btn.setObjectName("add_laser_btn")
        self.nav_layout.addWidget(self.add_laser_btn, 0, 2, 1, 1)
        self.label_material = QtWidgets.QLabel(parent=self.nav_group)
        self.label_material.setObjectName("label_material")
        self.nav_layout.addWidget(self.label_material, 1, 0, 1, 1)
        self.edit_laser_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.edit_laser_btn.setObjectName("edit_laser_btn")
        self.nav_layout.addWidget(self.edit_laser_btn, 0, 3, 1, 1)
        self.add_material_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.add_material_btn.setObjectName("add_material_btn")
        self.nav_layout.addWidget(self.add_material_btn, 1, 2, 1, 1)
        self.material_combo = QtWidgets.QComboBox(parent=self.nav_group)
        self.material_combo.setObjectName("material_combo")
        self.nav_layout.addWidget(self.material_combo, 1, 1, 1, 1)
        self.edit_material_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.edit_material_btn.setObjectName("edit_material_btn")
        self.nav_layout.addWidget(self.edit_material_btn, 1, 3, 1, 1)
        self.remove_material_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.remove_material_btn.setObjectName("remove_material_btn")
        self.nav_layout.addWidget(self.remove_material_btn, 1, 4, 1, 1)
        self.label_type = QtWidgets.QLabel(parent=self.nav_group)
        self.label_type.setObjectName("label_type")
        self.nav_layout.addWidget(self.label_type, 2, 0, 1, 1)
        self.type_combo = QtWidgets.QComboBox(parent=self.nav_group)
        self.type_combo.setObjectName("type_combo")
        self.nav_layout.addWidget(self.type_combo, 2, 1, 1, 1)
        self.add_type_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.add_type_btn.setObjectName("add_type_btn")
        self.nav_layout.addWidget(self.add_type_btn, 2, 2, 1, 1)
        self.edit_type_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.edit_type_btn.setObjectName("edit_type_btn")
        self.nav_layout.addWidget(self.edit_type_btn, 2, 3, 1, 1)
        self.remove_type_btn = QtWidgets.QPushButton(parent=self.nav_group)
        self.remove_type_btn.setObjectName("remove_type_btn")
        self.nav_layout.addWidget(self.remove_type_btn, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.nav_group)
        self.label_2.setObjectName("label_2")
        self.nav_layout.addWidget(self.label_2, 3, 0, 1, 1)
        self.postprocessing_combobox = QtWidgets.QComboBox(parent=self.nav_group)
        self.postprocessing_combobox.setObjectName("postprocessing_combobox")
        self.nav_layout.addWidget(self.postprocessing_combobox, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.nav_group)
        self.label_3.setObjectName("label_3")
        self.nav_layout.addWidget(self.label_3, 3, 1, 1, 1)
        self.laser_mode_combobox = QtWidgets.QComboBox(parent=self.nav_group)
        self.laser_mode_combobox.setObjectName("laser_mode_combobox")
        self.nav_layout.addWidget(self.laser_mode_combobox, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.nav_group)
        self.label_4.setObjectName("label_4")
        self.nav_layout.addWidget(self.label_4, 3, 2, 1, 1)
        self.enclosure_fan_spinbox = QtWidgets.QSpinBox(parent=self.nav_group)
        self.enclosure_fan_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.enclosure_fan_spinbox.setMaximum(100)
        self.enclosure_fan_spinbox.setObjectName("enclosure_fan_spinbox")
        self.nav_layout.addWidget(self.enclosure_fan_spinbox, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.nav_group)
        self.label.setObjectName("label")
        self.nav_layout.addWidget(self.label, 3, 3, 1, 1)
        self.air_assist_combobox = QtWidgets.QComboBox(parent=self.nav_group)
        self.air_assist_combobox.setObjectName("air_assist_combobox")
        self.nav_layout.addWidget(self.air_assist_combobox, 4, 3, 1, 1)
        self.gridLayout.addWidget(self.nav_group, 0, 0, 1, 1)

        self.retranslateUi(DatabaseNavigatorWidget)
        QtCore.QMetaObject.connectSlotsByName(DatabaseNavigatorWidget)

    def retranslateUi(self, DatabaseNavigatorWidget):
        _translate = QtCore.QCoreApplication.translate
        DatabaseNavigatorWidget.setWindowTitle(_translate("DatabaseNavigatorWidget", "Database Navigator"))
        self.palette_group.setTitle(_translate("DatabaseNavigatorWidget", "Color Palette"))
        self.editor_group.setTitle(_translate("DatabaseNavigatorWidget", "Parameter Settings"))
        self.label_color_name.setText(_translate("DatabaseNavigatorWidget", "Color Name:"))
        self.save_params_btn.setText(_translate("DatabaseNavigatorWidget", "Save Parameter Changes"))
        self.label_hatch.setText(_translate("DatabaseNavigatorWidget", "Hatch Distance (mm):"))
        self.label_power.setText(_translate("DatabaseNavigatorWidget", "Laser Power (%):"))
        self.color_rgb_label.setText(_translate("DatabaseNavigatorWidget", "N/A"))
        self.label_color_rgb.setText(_translate("DatabaseNavigatorWidget", "Color RGB:"))
        self.label_hatch_pattern.setText(_translate("DatabaseNavigatorWidget", "Hatch Pattern:"))
        self.label_hatch_angle.setText(_translate("DatabaseNavigatorWidget", "Hatch Angle (°):"))
        self.label_speed.setText(_translate("DatabaseNavigatorWidget", "Speed (mm/min):"))
        self.add_color_btn.setText(_translate("DatabaseNavigatorWidget", "Add"))
        self.remove_color_btn.setText(_translate("DatabaseNavigatorWidget", "Remove"))
        self.nav_group.setTitle(_translate("DatabaseNavigatorWidget", "Database Selection"))
        self.label_laser.setText(_translate("DatabaseNavigatorWidget", "Laser:"))
        self.remove_laser_btn.setText(_translate("DatabaseNavigatorWidget", "-"))
        self.add_laser_btn.setText(_translate("DatabaseNavigatorWidget", "+"))
        self.label_material.setText(_translate("DatabaseNavigatorWidget", "Material:"))
        self.edit_laser_btn.setText(_translate("DatabaseNavigatorWidget", "Edit"))
        self.add_material_btn.setText(_translate("DatabaseNavigatorWidget", "+"))
        self.edit_material_btn.setText(_translate("DatabaseNavigatorWidget", "Edit"))
        self.remove_material_btn.setText(_translate("DatabaseNavigatorWidget", "-"))
        self.label_type.setText(_translate("DatabaseNavigatorWidget", "Material Type:"))
        self.add_type_btn.setText(_translate("DatabaseNavigatorWidget", "+"))
        self.edit_type_btn.setText(_translate("DatabaseNavigatorWidget", "Edit"))
        self.remove_type_btn.setText(_translate("DatabaseNavigatorWidget", "-"))
        self.label_2.setText(_translate("DatabaseNavigatorWidget", "Post Processing"))
        self.label_3.setText(_translate("DatabaseNavigatorWidget", "Laser Mode"))
        self.label_4.setText(_translate("DatabaseNavigatorWidget", "Enclosure Fan"))
        self.label.setText(_translate("DatabaseNavigatorWidget", "air assist"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DatabaseNavigatorWidget = QtWidgets.QWidget()
    ui = Ui_DatabaseNavigatorWidget()
    ui.setupUi(DatabaseNavigatorWidget)
    DatabaseNavigatorWidget.show()
    sys.exit(app.exec())
